### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by jtbeales** [ryanjamurphy/Create-flashcards-in-Anki-from-PDFs-using-Skim-and-DEVONthink-#2]
Hi!

I'm really excited by the possibility of this, but I can't get it to work for me. In the README, it simply says "Run the script on a PDF with highlighted text." Could we get more detailed usage directions here? I'm going to dig into the code itself, but people without a programming background probably wouldn't be able to do that.

Thank you, and great work!

Jeremy

**Comment by ryanjamurphy** [comment]
> Could we get more detailed usage directions here? 

Hmm. It's been so long since I've used the script that I'm not sure I even recall how I was invoking it. 

I _think_ it was just "run the script (e.g., double click on it), then select your file". Let me know if that's not the case!

**Comment by jtbeales** [comment]
Thanks for getting back to me! Opening it in script editor and running it from there worked for me. However, it no longer works as is due to some changes that have been made (not sure if it's an apple issue or a skim issue). I'm still in the process of debugging it (and making progress), but maybe I'll make my version available to people once I finish. Thank you!
